lint:
  actions_ci: false
  files_exist:
    - lib/nfcore_external_java_deps.jar
    - conf/modules.config
  modules_config: false
nf_core_version: 3.0.2
org_path:
repository_type: pipeline
template:
  author: Phil Ewels, Sateesh Peri
  description: Methylation (Bisulfite-Sequencing) Best Practice analysis pipeline,
    part of the nf-core community.
  force: false
  is_nfcore: true
  name: methylseq
  org: nf-core
  outdir: .
  skip_features:
  version: 2.7.1
update:
