name: "Get number of shards"
description: "Get the number of nf-test shards for the current CI job"
outputs:
  shard:
    description: "Array of shard numbers"
    value: ${{ steps.shards.outputs.shards }}
  total_shards:
    description: "Total number of shards"
    value: ${{ steps.shards.outputs.total_shards }}

runs:
  using: "composite"
  steps:
    - name: Install nf-test
      uses: nf-core/setup-nf-test@v1
      with:
        version: ${{ env.NFT_VER }}
        install-pdiff: true

    - name: Get number of shards
      id: shards
      shell: bash
      run: |
        # Run nf-test to get the number of related tests
        nftest_output=$(nf-test test --dry-run --changed-since HEAD^ --filter pipeline)
        echo "nf-test dry-run output: $nftest_output"

        # Default values for shard and total_shards
        shard="[]"
        total_shards=0

        # Check if there are related tests
        if echo "$nftest_output" | grep -q 'Found 0 related test(s)'; then
          echo "No related tests found."
        else
          # Extract the number of related tests
          number_of_shards=$(echo "$nftest_output" | grep -o 'Found [0-9]* related test' | tail -1 | awk '{print $2}')
          if [[ -n "$number_of_shards" && "$number_of_shards" -gt 0 ]]; then
            shard=$(seq 1 "$number_of_shards" | jq -R . | jq -c -s .)
            total_shards="$number_of_shards"
          else
            echo "Unexpected output format. Falling back to default values."
          fi
        fi

        # Write to GitHub Actions outputs
        echo "shard=$shard" >> $GITHUB_OUTPUT
        echo "total_shards=$total_shards" >> $GITHUB_OUTPUT

        # Debugging output
        echo "Final shard array: $shard"
        echo "Total number of shards: $total_shards"
